# IELTS high-frequency vocabulary — organized by topic
# Format: (word, part_of_speech, example_sentence, chinese_meaning)

VOCABULARY = {
    "01 教育与学习 Education": [
        ("academic", "adj.", "She has a strong academic background in biology.", "学术的"),
        ("acquire", "v.", "Students acquire knowledge through practice.", "获得；习得"),
        ("assess", "v.", "Teachers assess students' progress regularly.", "评估"),
        ("assignment", "n.", "I have a writing assignment due next week.", "作业；任务"),
        ("attend", "v.", "Over 200 students attend the lecture.", "参加；出席"),
        ("campus", "n.", "The university campus is very large.", "校园"),
        ("curriculum", "n.", "The school revised its curriculum last year.", "课程；课程体系"),
        ("discipline", "n.", "Physics is a challenging discipline.", "学科；纪律"),
        ("educate", "v.", "Schools aim to educate the whole person.", "教育"),
        ("enroll", "v.", "She enrolled in a language course.", "注册；入学"),
        ("faculty", "n.", "The faculty includes experts from many fields.", "院系；全体教员"),
        ("graduate", "v./n.", "He graduated from university in 2020.", "毕业；毕业生"),
        ("lecture", "n.", "The professor gave a lecture on climate change.", "讲座；讲课"),
        ("literacy", "n.", "Digital literacy is essential today.", "读写能力；素养"),
        ("major", "n./v.", "She majors in economics.", "专业；主修"),
        ("qualification", "n.", "You need a teaching qualification.", "资格；学历"),
        ("scholarship", "n.", "He won a scholarship to study abroad.", "奖学金"),
        ("seminar", "n.", "We discussed the topic in a small seminar.", "研讨会"),
        ("tuition", "n.", "Tuition fees have increased this year.", "学费"),
        ("undergraduate", "n.", "She is an undergraduate student.", "本科生"),
    ],
    "02 环境与能源 Environment": [
        ("atmosphere", "n.", "Pollution damages the Earth's atmosphere.", "大气；氛围"),
        ("biodiversity", "n.", "Rainforests are rich in biodiversity.", "生物多样性"),
        ("carbon", "n.", "Countries aim to reduce carbon emissions.", "碳"),
        ("climate", "n.", "Climate change affects global weather.", "气候"),
        ("conservation", "n.", "Wildlife conservation is a global priority.", "保护；保存"),
        ("contaminate", "v.", "Chemicals can contaminate drinking water.", "污染"),
        ("deforestation", "n.", "Deforestation threatens many species.", "滥伐森林"),
        ("drought", "n.", "The region suffered from severe drought.", "干旱"),
        ("ecosystem", "n.", "Coral reefs are fragile ecosystems.", "生态系统"),
        ("emission", "n.", "Vehicle emissions contribute to air pollution.", "排放；排放物"),
        ("endangered", "adj.", "The tiger is an endangered species.", "濒危的"),
        ("erosion", "n.", "Soil erosion is worsened by deforestation.", "侵蚀"),
        ("habitat", "n.", "Urban expansion destroys natural habitats.", "栖息地"),
        ("pollution", "n.", "Air pollution is a serious health risk.", "污染"),
        ("recycle", "v.", "We should recycle plastic and paper.", "回收利用"),
        ("renewable", "adj.", "Solar power is a renewable energy source.", "可再生的"),
        ("resource", "n.", "Water is a precious natural resource.", "资源"),
        ("sustainable", "adj.", "We need sustainable farming methods.", "可持续的"),
        ("threaten", "v.", "Rising seas threaten coastal cities.", "威胁"),
        ("wildlife", "n.", "The park protects local wildlife.", "野生动物"),
    ],
    "03 科技与创新 Technology": [
        ("access", "n./v.", "Everyone should have access to the internet.", "访问；通道；获取"),
        ("artificial", "adj.", "Artificial intelligence is changing industries.", "人工的；人造的"),
        ("automation", "n.", "Automation has replaced many routine jobs.", "自动化"),
        ("device", "n.", "This device can monitor your heart rate.", "设备；装置"),
        ("digital", "adj.", "Digital tools make learning more flexible.", "数字的"),
        ("efficient", "adj.", "New engines are more fuel-efficient.", "高效的"),
        ("innovation", "n.", "Innovation drives economic growth.", "创新"),
        ("install", "v.", "Please install the latest software update.", "安装"),
        ("internet", "n.", "The internet connects people worldwide.", "互联网"),
        ("invent", "v.", "Who invented the telephone?", "发明"),
        ("mechanism", "n.", "Scientists study the mechanism of the disease.", "机制；原理"),
        ("network", "n.", "The computer network crashed yesterday.", "网络"),
        ("operate", "v.", "Do you know how to operate this machine?", "操作；运转"),
        ("robot", "n.", "Robots are used in modern factories.", "机器人"),
        ("satellite", "n.", "Satellites help us forecast the weather.", "卫星"),
        ("software", "n.", "She develops software for mobile phones.", "软件"),
        ("technical", "adj.", "The report is too technical for most readers.", "技术的"),
        ("technology", "n.", "Technology has transformed communication.", "技术"),
        ("virtual", "adj.", "Many meetings are now held in virtual spaces.", "虚拟的"),
        ("wireless", "adj.", "The hotel offers free wireless internet.", "无线的"),
    ],
    "04 健康与医疗 Health": [
        ("alleviate", "v.", "Medicine can alleviate pain.", "减轻；缓解"),
        ("chronic", "adj.", "Diabetes is a chronic condition.", "慢性的；长期的"),
        ("diagnose", "v.", "The doctor diagnosed the illness early.", "诊断"),
        ("diet", "n.", "A balanced diet is important for health.", "饮食"),
        ("disorder", "n.", "He was treated for a sleep disorder.", "失调；疾病"),
        ("epidemic", "n.", "The epidemic spread rapidly.", "流行病"),
        ("fitness", "n.", "Regular exercise improves fitness.", "健康；体能"),
        ("immune", "adj.", "Vaccines help build immune protection.", "免疫的"),
        ("infection", "n.", "Wash your hands to prevent infection.", "感染"),
        ("nutrition", "n.", "Good nutrition supports child development.", "营养"),
        ("obesity", "n.", "Obesity increases the risk of heart disease.", "肥胖"),
        ("organ", "n.", "The heart is a vital organ.", "器官"),
        ("physical", "adj.", "Physical activity reduces stress.", "身体的；物理的"),
        ("prevent", "v.", "Vaccines help prevent serious illness.", "预防"),
        ("psychological", "adj.", "Stress has psychological effects.", "心理的"),
        ("symptom", "n.", "Fever is a common symptom of flu.", "症状"),
        ("therapy", "n.", "She received physical therapy after the injury.", "治疗；疗法"),
        ("treatment", "n.", "The treatment was effective.", "治疗"),
        ("vaccine", "n.", "The vaccine protects against the virus.", "疫苗"),
        ("wellbeing", "n.", "Mental wellbeing matters as much as physical health.", "健康；幸福"),
    ],
    "05 社会与文化 Society": [
        ("ancestor", "n.", "Our ancestors lived without modern technology.", "祖先"),
        ("community", "n.", "The local community organized a festival.", "社区"),
        ("conflict", "n.", "The conflict lasted for several years.", "冲突"),
        ("culture", "n.", "Every culture has its own traditions.", "文化"),
        ("custom", "n.", "It is a local custom to remove shoes indoors.", "习俗；风俗"),
        ("diverse", "adj.", "The city has a diverse population.", "多样的"),
        ("ethnic", "adj.", "The area has many ethnic groups.", "民族的；种族的"),
        ("generation", "n.", "Each generation faces different challenges.", "一代人"),
        ("heritage", "n.", "The temple is part of our cultural heritage.", "遗产"),
        ("identity", "n.", "Language is central to cultural identity.", "身份；认同"),
        ("immigrant", "n.", "Many immigrants seek better opportunities.", "移民"),
        ("inequality", "n.", "Income inequality remains a social problem.", "不平等"),
        ("minority", "n.", "Minorities should have equal rights.", "少数群体"),
        ("population", "n.", "The world population continues to grow.", "人口"),
        ("poverty", "n.", "Efforts are made to reduce poverty.", "贫困"),
        ("tradition", "n.", "The festival is an old tradition.", "传统"),
        ("urban", "adj.", "Urban areas are often crowded.", "城市的"),
        ("violence", "n.", "The report discusses domestic violence.", "暴力"),
        ("volunteer", "n./v.", "She works as a volunteer at the hospital.", "志愿者；自愿做"),
        ("welfare", "n.", "The government provides social welfare.", "福利"),
    ],
    "06 工作与商业 Work & Business": [
        ("career", "n.", "She built a successful career in finance.", "职业；生涯"),
        ("colleague", "n.", "My colleague helped me with the project.", "同事"),
        ("commercial", "adj.", "The building is used for commercial purposes.", "商业的"),
        ("compete", "v.", "Companies compete for market share.", "竞争"),
        ("consumer", "n.", "Consumers prefer affordable products.", "消费者"),
        ("corporate", "adj.", "Corporate culture affects employee satisfaction.", "企业的"),
        ("employ", "v.", "The factory employs over 500 workers.", "雇用"),
        ("enterprise", "n.", "Small enterprises create many jobs.", "企业"),
        ("income", "n.", "His income increased after the promotion.", "收入"),
        ("industry", "n.", "The tourism industry is recovering.", "行业；工业"),
        ("invest", "v.", "They decided to invest in renewable energy.", "投资"),
        ("manage", "v.", "She manages a team of twenty people.", "管理"),
        ("occupation", "n.", "Please state your occupation on the form.", "职业"),
        ("profit", "n.", "The company reported higher profits.", "利润"),
        ("promote", "v.", "Hard work can help you get promoted.", "晋升；促进"),
        ("revenue", "n.", "Online sales boosted the company's revenue.", "收入；营收"),
        ("salary", "n.", "The job offers a competitive salary.", "薪水"),
        ("staff", "n.", "The hotel staff were very helpful.", "员工"),
        ("unemployment", "n.", "Unemployment rose during the recession.", "失业"),
        ("workforce", "n.", "The workforce needs new skills.", "劳动力"),
    ],
    "07 政府与法律 Government": [
        ("authority", "n.", "The local authority approved the plan.", "当局；权威"),
        ("ban", "v./n.", "The government banned smoking in public places.", "禁止"),
        ("citizen", "n.", "Every citizen has rights and duties.", "公民"),
        ("democracy", "n.", "Democracy depends on free elections.", "民主"),
        ("enforce", "v.", "Police enforce traffic laws.", "执行；实施"),
        ("fund", "v./n.", "The project is funded by the government.", "资助；资金"),
        ("illegal", "adj.", "It is illegal to drive without a licence.", "非法的"),
        ("legislation", "n.", "New legislation was passed last month.", "立法；法律"),
        ("policy", "n.", "The school has a strict attendance policy.", "政策"),
        ("regulate", "v.", "Laws regulate food safety standards.", "监管；规范"),
        ("regulation", "n.", "There are strict regulations on emissions.", "规定；法规"),
        ("reform", "n./v.", "The country needs economic reform.", "改革"),
        ("tax", "n./v.", "Income tax funds public services.", "税；征税"),
        ("vote", "v./n.", "Citizens vote in national elections.", "投票"),
        ("implement", "v.", "The government will implement new safety rules.", "实施"),
    ],
    "08 科研与学术 Research": [
        ("analysis", "n.", "The analysis supports our hypothesis.", "分析"),
        ("approach", "n.", "We need a new approach to the problem.", "方法；途径"),
        ("assume", "v.", "Don't assume the results are correct.", "假设；认为"),
        ("conduct", "v.", "Scientists conducted a series of experiments.", "进行；实施"),
        ("conclude", "v.", "The study concluded that exercise helps.", "得出结论"),
        ("data", "n.", "The data were collected over five years.", "数据"),
        ("demonstrate", "v.", "The experiment demonstrates the theory.", "证明；展示"),
        ("evidence", "n.", "There is strong evidence for climate change.", "证据"),
        ("experiment", "n.", "The experiment produced unexpected results.", "实验"),
        ("factor", "n.", "Cost is an important factor.", "因素"),
        ("finding", "n.", "The findings were published in a journal.", "发现；研究结果"),
        ("hypothesis", "n.", "The hypothesis was tested in the lab.", "假设"),
        ("method", "n.", "Researchers used a standard method.", "方法"),
        ("observe", "v.", "Astronomers observe distant galaxies.", "观察"),
        ("phenomenon", "n.", "Migration is a complex phenomenon.", "现象"),
        ("publish", "v.", "She published her first paper last year.", "发表；出版"),
        ("theory", "n.", "Darwin's theory changed biology.", "理论"),
        ("variable", "n.", "Temperature is a key variable.", "变量"),
        ("volume", "n.", "The journal published a new volume.", "卷；量"),
    ],
    "09 媒体与沟通 Media": [
        ("advertise", "v.", "Companies advertise on social media.", "做广告"),
        ("audience", "n.", "The audience applauded at the end.", "观众；受众"),
        ("broadcast", "v./n.", "The interview was broadcast live.", "广播；播出"),
        ("channel", "n.", "The news channel reported the story.", "频道；渠道"),
        ("communicate", "v.", "Good leaders communicate clearly.", "交流；沟通"),
        ("journalist", "n.", "The journalist interviewed the minister.", "记者"),
        ("media", "n.", "Social media influences public opinion.", "媒体"),
        ("publish", "v.", "The newspaper published the article.", "出版；发表"),
        ("publicity", "n.", "The event received a lot of publicity.", "宣传；关注"),
        ("source", "n.", "Always check the source of information.", "来源"),
        ("subscribe", "v.", "I subscribe to an online magazine.", "订阅"),
        ("transfer", "v.", "Data can be transferred instantly.", "转移；传输"),
        ("transmit", "v.", "The station transmits radio signals.", "传输；传播"),
        ("trend", "n.", "Remote work is a growing trend.", "趋势"),
        ("via", "prep.", "We contacted them via email.", "通过"),
    ],
    "10 通用学术词汇 Academic Words": [
        ("achieve", "v.", "She achieved her goal through hard work.", "实现；达到"),
        ("adequate", "adj.", "The salary is barely adequate.", "足够的"),
        ("alternative", "n./adj.", "We need an alternative solution.", "替代方案；可供替代的"),
        ("benefit", "n./v.", "Exercise has many health benefits.", "好处；有益于"),
        ("capacity", "n.", "The hall has a capacity of 500.", "容量；能力"),
        ("concept", "n.", "The concept is difficult to explain.", "概念"),
        ("consequence", "n.", "Every action has consequences.", "后果"),
        ("considerable", "adj.", "The project requires considerable effort.", "相当大的"),
        ("contribute", "v.", "Many factors contribute to success.", "贡献；促成"),
        ("decline", "v./n.", "Sales declined last quarter.", "下降；衰退"),
        ("despite", "prep.", "Despite the rain, the event continued.", "尽管"),
        ("domestic", "adj.", "Domestic demand has increased.", "国内的；家庭的"),
        ("establish", "v.", "The university was established in 1890.", "建立"),
        ("estimate", "v./n.", "Experts estimate the cost at $2 million.", "估计"),
        ("feature", "n./v.", "Safety is a key feature of the design.", "特征；以…为特色"),
        ("function", "n./v.", "The main function of schools is education.", "功能；运转"),
        ("impact", "n./v.", "Technology has a huge impact on society.", "影响"),
        ("indicate", "v.", "The results indicate a clear trend.", "表明"),
        ("instance", "n.", "This is a classic instance of bias.", "例子；实例"),
        ("issue", "n.", "Climate change is a global issue.", "问题；议题"),
        ("maintain", "v.", "It is hard to maintain motivation.", "维持；坚持"),
        ("obtain", "v.", "You must obtain permission first.", "获得"),
        ("potential", "n./adj.", "The region has great economic potential.", "潜力；潜在的"),
        ("previous", "adj.", "Refer to the previous chapter.", "以前的"),
        ("primary", "adj.", "Our primary concern is safety.", "主要的；初级的"),
        ("principle", "n.", "He explained the basic principles.", "原则"),
        ("process", "n./v.", "Learning is a gradual process.", "过程；处理"),
        ("require", "v.", "The job requires good communication skills.", "需要；要求"),
        ("significant", "adj.", "There was a significant improvement.", "重要的；显著的"),
        ("structure", "n.", "The essay needs a clear structure.", "结构"),
    ],
}
