#!/usr/bin/env python3
"""Generate paragraph Chinese translations via MyMemory API (sentence-chunked)."""

import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from ielts_reading_passages import PASSAGES

OUT_PATH = os.path.join(ROOT, "ielts_reading_translations.py")
CACHE_PATH = os.path.join(ROOT, "data", "translation_cache.json")
MAX_CHARS = 450
SENT_SPLIT = re.compile(r"(?<=[.!?])\s+")


def split_sentences(text):
    parts = SENT_SPLIT.split(text.strip())
    return [p.strip() for p in parts if p.strip()]


def chunk_sentences(sentences):
    chunks = []
    current = ""
    for sentence in sentences:
        candidate = f"{current} {sentence}".strip() if current else sentence
        if len(candidate) <= MAX_CHARS:
            current = candidate
        else:
            if current:
                chunks.append(current)
            if len(sentence) <= MAX_CHARS:
                current = sentence
            else:
                for i in range(0, len(sentence), MAX_CHARS):
                    part = sentence[i : i + MAX_CHARS]
                    if i + MAX_CHARS >= len(sentence):
                        current = part
                    else:
                        chunks.append(part)
                if len(sentence) > MAX_CHARS:
                    current = ""
    if current:
        chunks.append(current)
    return chunks


def translate_en_zh(text, retries=6):
    params = urllib.parse.urlencode({"q": text, "langpair": "en|zh-CN"})
    url = f"https://api.mymemory.translated.net/get?{params}"
    for attempt in range(retries):
        try:
            req = urllib.request.Request(
                url, headers={"User-Agent": "CatchLittleFish/1.0"}
            )
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.load(resp)
            if data.get("responseStatus") != 200:
                detail = data.get("responseDetails") or str(data)
                if "429" in detail or "MYMEMORY WARNING" in detail.upper():
                    raise urllib.error.HTTPError(url, 429, detail, None, None)
                raise RuntimeError(detail)
            return data["responseData"]["translatedText"].strip()
        except urllib.error.HTTPError as err:
            if err.code == 429 and attempt < retries - 1:
                wait = 8 * (attempt + 1)
                print(f"    rate limited, wait {wait}s...")
                time.sleep(wait)
                continue
            raise
    raise RuntimeError("translate failed after retries")


def translate_paragraph(text):
    sentences = split_sentences(text)
    chunks = chunk_sentences(sentences)
    zh_parts = []
    for chunk in chunks:
        zh_parts.append(translate_en_zh(chunk))
        time.sleep(1.2)
    return "".join(zh_parts)


def load_cache():
    if os.path.isfile(CACHE_PATH):
        with open(CACHE_PATH, encoding="utf-8") as f:
            return json.load(f)
    return {}


def save_cache(cache):
    os.makedirs(os.path.dirname(CACHE_PATH), exist_ok=True)
    with open(CACHE_PATH, "w", encoding="utf-8") as f:
        json.dump(cache, f, ensure_ascii=False, indent=2)


def write_output(translations):
    lines = [
        "# Chinese translations for IELTS reading passages (paragraph-aligned with PASSAGES text)",
        "# Auto-generated by scripts/generate_translations.py",
        "",
        "TRANSLATIONS = " + json.dumps(translations, ensure_ascii=False, indent=4),
        "",
    ]
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    cache = load_cache()
    translations = {int(k): v for k, v in cache.items()}

    for passage in PASSAGES:
        pid = passage["id"]
        paras = passage["text"].split("\n\n")
        if str(pid) in cache and len(cache[str(pid)]) == len(paras):
            print(f"Article {pid}: cached")
            continue

        print(f"Article {pid} ({len(paras)} paragraphs)")
        zh_list = []
        for idx, para in enumerate(paras, 1):
            print(f"  paragraph {idx}...")
            zh_list.append(translate_paragraph(para))
        translations[pid] = zh_list
        cache[str(pid)] = zh_list
        save_cache(cache)
        write_output(translations)

    write_output(translations)
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
